INSERT INTO COURSE (TITLE) VALUES ('DAM');
INSERT INTO COURSE (TITLE) VALUES ('DAW');
INSERT INTO COURSE (TITLE) VALUES ('ASIX');
INSERT INTO COURSE (TITLE) VALUES ('SMX');
INSERT INTO COURSE_MATERIAL (URL,COURSE_ID) VALUES ('PRUEBA',1);
INSERT INTO COURSE_MATERIAL (URL,COURSE_ID) VALUES ('PRUEBA2',1);
INSERT INTO COURSE_MATERIAL (URL,COURSE_ID) VALUES ('PRUEBA3',3);
INSERT INTO COURSE_MATERIAL (URL,COURSE_ID) VALUES ('PRUEBA4',3);

