INSERT INTO COURSE (TITLE) VALUES ('DAM');
INSERT INTO COURSE (TITLE) VALUES ('DAW');
INSERT INTO COURSE (TITLE) VALUES ('ASIX');
INSERT INTO COURSE (TITLE) VALUES ('SMX');
INSERT INTO COURSE_MATERIAL (URL) VALUES ('PRUEBA');
INSERT INTO COURSE_MATERIAL (URL) VALUES ('PRUEBA2');
INSERT INTO COURSE_MATERIAL (URL) VALUES ('PRUEBA3');
INSERT INTO COURSE_MATERIAL (URL) VALUES ('PRUEBA4');

